Repository AY1920S2-CS2103T-F11-1/main, pull requests merged in 2020-04, with the labels that each got.

#206 Eugene's v1.4 Contributions.
  docs/UserGuide.adoc
  src/main/java/life/calgo/commons/core/Config.java
  src/main/java/life/calgo/commons/core/LogsCenter.java
  src/main/java/life/calgo/commons/core/Messages.java
  src/main/java/life/calgo/commons/core/index/Index.java
  src/main/java/life/calgo/commons/util/StringUtil.java
  src/main/java/life/calgo/logic/Logic.java
  src/main/java/life/calgo/logic/commands/ExportCommand.java
  src/main/java/life/calgo/logic/commands/FindCommand.java
  src/main/java/life/calgo/logic/commands/ListCommand.java
  src/main/java/life/calgo/logic/parser/ArgumentMultimap.java
  src/main/java/life/calgo/logic/parser/DeleteCommandParser.java
  src/main/java/life/calgo/logic/parser/FindCommandParser.java
  src/main/java/life/calgo/logic/parser/FoodRecordParser.java
  src/main/java/life/calgo/logic/parser/ParserUtil.java
  src/main/java/life/calgo/logic/parser/exceptions/ParseException.java
  src/main/java/life/calgo/model/FoodRecord.java
  src/main/java/life/calgo/model/Model.java
  src/main/java/life/calgo/model/ModelManager.java
  src/main/java/life/calgo/model/ReadOnlyFoodRecord.java
  src/main/java/life/calgo/model/UserPrefs.java
  src/main/java/life/calgo/model/food/Calorie.java
  src/main/java/life/calgo/model/food/Carbohydrate.java
  src/main/java/life/calgo/model/food/Fat.java
  src/main/java/life/calgo/model/food/Food.java
  src/main/java/life/calgo/model/food/Name.java
  src/main/java/life/calgo/model/food/Protein.java
  src/main/java/life/calgo/model/food/predicates/CalorieContainsKeywordsPredicate.java
  src/main/java/life/calgo/model/food/predicates/CarbohydrateContainsKeywordsPredicate.java
  src/main/java/life/calgo/model/food/predicates/FatContainsKeywordsPredicate.java
  src/main/java/life/calgo/model/food/predicates/NameContainsKeywordsPredicate.java
  src/main/java/life/calgo/model/food/predicates/ProteinContainsKeywordsPredicate.java
  src/main/java/life/calgo/model/food/predicates/TagContainsKeywordsPredicate.java
  src/main/java/life/calgo/model/tag/Tag.java
  src/main/java/life/calgo/model/util/SampleDataUtil.java
  src/main/java/life/calgo/storage/ConsumptionRecordStorage.java
  src/main/java/life/calgo/storage/DocumentGenerator.java
  src/main/java/life/calgo/storage/ExportGenerator.java
  src/main/java/life/calgo/storage/FoodRecordStorage.java
  src/main/java/life/calgo/storage/GoalStorage.java
  src/main/java/life/calgo/storage/JsonAdaptedFood.java
  src/main/java/life/calgo/storage/JsonAdaptedGoal.java
  src/main/java/life/calgo/storage/JsonAdaptedTag.java
  src/main/java/life/calgo/storage/JsonConsumptionRecordStorage.java
  src/main/java/life/calgo/storage/JsonFoodRecordStorage.java
  src/main/java/life/calgo/storage/JsonGoalStorage.java
  src/main/java/life/calgo/storage/JsonSerializableFoodRecord.java
  src/main/java/life/calgo/storage/JsonUserPrefsStorage.java
  src/main/java/life/calgo/storage/ReportGenerator.java
  src/main/java/life/calgo/storage/Storage.java
  src/main/java/life/calgo/storage/StorageManager.java
  src/test/java/life/calgo/logic/commands/FindCommandTest.java
  src/test/java/life/calgo/logic/commands/UpdateCommandTest.java
  src/test/java/life/calgo/logic/parser/FindCommandParserTest.java
  src/test/java/life/calgo/testutil/TypicalFoodItems.java
Labels: priority.High, severity.Medium, status.Ongoing, type.Bug, type.Task

#217 Update UG for find, list, export, introduction and FAQ.
  docs/UserGuide.adoc
  src/main/java/life/calgo/logic/parser/FindCommandParser.java
  src/main/java/life/calgo/logic/parser/ParserUtil.java
  src/main/java/life/calgo/model/food/Calorie.java
  src/main/java/life/calgo/model/food/Carbohydrate.java
  src/main/java/life/calgo/model/food/Fat.java
  src/main/java/life/calgo/model/food/Protein.java
  src/test/java/life/calgo/logic/parser/FindCommandParserTest.java
Labels: priority.High, type.Task

#226 Update DG section on Storage.
  docs/DeveloperGuide.adoc
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
  src/main/java/life/calgo/storage/StorageManager.java
Labels: priority.High, type.Task

#228 Add suggestions ability to report
  src/main/java/life/calgo/model/day/DailyFoodLog.java
  src/main/java/life/calgo/storage/DocumentGenerator.java
  src/main/java/life/calgo/storage/ExportGenerator.java
  src/main/java/life/calgo/storage/ReportGenerator.java
Labels: priority.High, type.Enhancement
